# Generated by Django 3.0.3 on 2020-02-26 09:19

import django.core.validators
from django.db import migrations, models

from video_transcoding import defaults


class Migration(migrations.Migration):
    dependencies = [
        ('video_transcoding', '0001_initial'),
    ]

    operations = []
    if defaults.VIDEO_MODEL == 'video_transcoding.Video':
        operations.extend([
            migrations.AlterField(
                model_name='video',
                name='source',
                field=models.URLField(validators=[
                    django.core.validators.URLValidator(
                        schemes=('http', 'https'))]),
            ),
        ])
