# Generated by Django 5.0.6 on 2024-07-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_transcoding', '0005_video_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='profile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
