# Generated by Django 5.0.7 on 2024-07-15 08:37

from django.db import migrations, models

from video_transcoding import defaults


class Migration(migrations.Migration):
    dependencies = [
        ('video_transcoding', '0005_video_metadata'),
    ]

    operations = []
    if defaults.VIDEO_MODEL == 'video_transcoding.Video':
        operations.extend([
            migrations.AddField(
                model_name='video',
                name='duration',
                field=models.DurationField(blank=True, null=True, verbose_name='duration'),
            ),
        ])
