# Generated by Django 5.0.7 on 2024-07-24 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_transcoding', '0006_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprofile',
            name='segment_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=4), verbose_name='segment duration'),
            preserve_default=False,
        ),
    ]
