name: documentation

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Pillow-9.5.0
    - name: Generate documentation
      run: |
        pip install -r docs/requirements.txt
        cd docs && make autodoc html
